import helpers from "../helpers.js"

export default function (wat) {
    return wat
        .replaceAll("(self)", "(global.get $self)")
        .replaceAll("(null)", "(ref.null extern)")
        .replaceAll("(func)", "(ref.null func)")
        .replaceAll("(this)", "(local.get 0)")
        .replaceAll("(array)", "(call $self.Array<>ext)")
        .replaceAll("(object)", "(call $self.Object<>ext)")
        .replaceAll("(console $", "(call $self.console.")
        .replaceAll("(reflect $", "(call $self.Reflect.")
        .replaceAll("(bigint $", "(call $self.BigInt.")
        .replaceAll("(number $", "(call $self.Number.")
        .replaceAll("(string $", "(call $self.String.")
        .replaceAll("(object $", "(call $self.Object.")
        .replaceAll("(array $", "(call $self.Array.")
        .replaceAll("(self $", "(ref.extern $self.")
        .replaceAll("(url $", "(ref.extern $self.URL.")
        .replaceAll(" mut ext)", " (mut externref) (null))")
        .replaceAll(" mut fun)", " (mut funcref) (func))")
        .replaceAll(" mut vec)", " (mut v128) (v128.const i32x4 0 0 0 0))")
        .replaceAll(" fun)", " funcref)")
        .replaceAll(" ext)", " externref)")
        .replaceAll(" != null)", ") (ref.is_null) (i32.eqz)")
        .replaceAll(" == null)", ") (ref.is_null)")
        .replaceAll(" == 0)", ") (i32.eqz)")
        .replaceAll(" == true)", ") (i32.const 1) (i32.eq)")
        .replaceAll(" == false)", ") (i32.eqz)")
        .replaceAll(" == nan)", ") (f32.const nan) (f32.eq)")
        .replaceAll(" != nan)", ") (f32.const nan) (f32.ne)")
        .replaceAll(" != undefined)", ") (self $undefined) (object $is<ext.ext>i32) (i32.eqz)")
        .replaceAll(" == undefined)", ") (self $undefined) (object $is<ext.ext>i32)")
        .replaceAll(" == \"\")", ") (string \"\") (object $is<ext.ext>i32)")
        .replaceAll(" != \"\")", ") (string \"\") (object $is<ext.ext>i32) (i32.eqz)")
        .replaceAll(/ mut\s+(i32|f32|i64|f64)\)/g, ` (mut $1) ($1.const 0))`)
        .replaceAll(/\<[A-Z](.[^>]*)\>/g, "externref")
        .replaceAll(/\(l(get|set|tee)(\s)/g, `(local.$1$2`)
        .replaceAll(/\(g(get|set)(\s)/g, `(global.$1$2`)
        .replaceAll(/\(t(get|set)(\s)/g, `(table.$1$2`)
        .replaceAll(/(i32|f32|i64|f64|fun|ext)\((\+|\-|)\s*([0-9\.]+)\)/g, `($1.const $2$3)`)
        .replaceAll(/\((.*)\.(set|tee)\s+([\+|\-])+\s+(\$.*)\s*\)/g, "($1.$2 $4 (i32.add ($1.get $4) (i32.const $31)))")
        .replaceAll(/\(apply(?:\.*)(i32|f32|i64|f64|fun|ext|)(\s*)/g, `(call $self.Reflect.apply<ext.ext.ext>$1 $2`)
        ;
}