#!/usr/bin/env node

import fs from "fs";

const headers = [`#!/usr/bin/env node`, `import fs from "fs";`, `import cp, { spawnSync } from "child_process";`].join("\n").concat("\n\n");
const index_js = fs.readFileSync("index.js", "utf8").split(/\n+/).filter(l => !l.startsWith("import") && !l.startsWith("#")).join("\n").concat("\n\n");
const cli_js = fs.readFileSync("cli.js", "utf8").split(/\n+/).filter(l => !l.startsWith("import")).join("\n").replaceAll("export ", "").concat("\n\n");
const helpers_js = fs.readFileSync("helpers.js", "utf8").split(/\n+/).filter(l => !l.startsWith("import") && !l.startsWith("export")).join("\n").concat("\n\n");
const clean_js = fs.readFileSync("clean.js", "utf8").split(/\n+/).filter(l => !l.startsWith("import")).join("\n").concat("\n\n").replaceAll("export default function", "function clean");
const imports = fs.readFileSync("index.js", "utf8").split(/\n+/).filter(l => l.startsWith("import") && l.includes("processors/")).map(i => i.split(/^import|\s+|from|\"|\.js/g).filter(Boolean))
    .map(([NAME, path]) => [NAME, process.cwd().concat(path.substring(1).concat(".js"))])
    .map(([NAME, path]) => [NAME, fs.readFileSync(path, "utf8")])
    .map(([NAME, code]) => code.split(/\n+/).filter(l => !l.startsWith("import")).join("\n").replaceAll("export default function", "function " + NAME).replaceAll("export ", ""))
    .join("\n\n");

const wat4beauty = fs.readFileSync("wat4beauty.js", "utf8");

if (fs.existsSync("../wat4wasm") === true) {
    fs.unlinkSync("../wat4wasm")
}

fs.writeFileSync("../wat4wasm",
    headers
        .concat(wat4beauty)
        .concat(helpers_js)
        .concat(imports)
        .concat(clean_js)
        .concat(cli_js)
        .concat(index_js)
);


fs.chmodSync("../wat4wasm", '755');
